setup:
  - name: Install dependencies
    command: |
      apt-get update
      apt-get install -y python3 python3-pip build-essential postgresql-client libpq-dev
      ln -s /usr/bin/python3 /usr/bin/python

build:
  - name: Install npm dependencies
    command: npm install --no-optional
  
  - name: Build Next.js app
    command: npm run build

  - name: Ensure output directory exists
    command: |
      mkdir -p /__app/out
      cp -r out/* /__app/out/ || true

run:
  command: npx serve -s out -l 3000