image: atlassian/default-image:3

pipelines:
  default:
    - step:
        name: Mirror to GitHub
        script:
          - apt-get update && apt-get install -y openssh-client git
          - mkdir -p ~/.ssh
          - echo "$GITHUB_DEPLOY_KEY" > ~/.ssh/id_ed25519
          - chmod 600 ~/.ssh/id_ed25519
          - ssh-keyscan github.com >> ~/.ssh/known_hosts

          - git clone --mirror git@bitbucket.org:paulworkspace12124/onlu.git
          - cd onlu.git
          - git remote set-url origin git@github.com:Tribeeox/onlu-backend.git
          - git push --mirror
